package com.hbln.smsintercept.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.hbln.smsintercept.db.bean.MobileBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MOBILE_BEAN".
*/
public class MobileBeanDao extends AbstractDao<MobileBean, String> {

    public static final String TABLENAME = "MOBILE_BEAN";

    /**
     * Properties of entity MobileBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Mobile = new Property(0, String.class, "mobile", true, "MOBILE");
    }


    public MobileBeanDao(DaoConfig config) {
        super(config);
    }
    
    public MobileBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MOBILE_BEAN\" (" + //
                "\"MOBILE\" TEXT PRIMARY KEY NOT NULL );"); // 0: mobile
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MOBILE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MobileBean entity) {
        stmt.clearBindings();
 
        String mobile = entity.getMobile();
        if (mobile != null) {
            stmt.bindString(1, mobile);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MobileBean entity) {
        stmt.clearBindings();
 
        String mobile = entity.getMobile();
        if (mobile != null) {
            stmt.bindString(1, mobile);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public MobileBean readEntity(Cursor cursor, int offset) {
        MobileBean entity = new MobileBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // mobile
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MobileBean entity, int offset) {
        entity.setMobile(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final String updateKeyAfterInsert(MobileBean entity, long rowId) {
        return entity.getMobile();
    }
    
    @Override
    public String getKey(MobileBean entity) {
        if(entity != null) {
            return entity.getMobile();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MobileBean entity) {
        return entity.getMobile() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
